name: Unit-Tests

# When should these jobs run
# Push to any of the branches
# Pull request for the master branch
on:
  push:
    # MAYB: only in master
    # branches: [ master ]
  pull_request:
    branches: [ master ]
    # MANUALLY
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    # Allow the Job to fail (e.g. for a specific emacs version)
    # and still continie with the other jobs
    continue-on-error: true
    strategy:
      matrix:
        emacs_version:
          # - '24.1'
          # - '24.2'
          # - '24.3'
          # - '24.4'
          # - '24.5'
          - '25.1'
          - '25.2'
          - '25.3'
          - '26.1'
          - '26.2'
          - '26.3'
          - '27.1'
    steps:
      - name: Set up emacs
        uses: purcell/setup-emacs@master
        # Run steps with emacs version specified in the matrix above
        with:
          version: ${{ matrix.emacs_version }}

      - name: Install Eldev
        run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh

      - name: Check out repository
        uses: actions/checkout@v2

        # For some unknown reason, mvtn-compat.el seems to not be loaded when
        # eldev test is run with the --packaged flag. Even weirder, it seems to
        # only happen the first time eldev test is run. Running it a second time
        # fixes the issue.
      - name: Run tests with eldev
        run: |
          eldev --packaged --debug --trace --time --color test || true
          eldev --packaged --debug --trace --time --color test